### ISSUE TITLE
Invalid package error

### ISSUE THREAD

**Issue by m0yP** [AbdurazaaqMohammed/AntiSplit-M#6] opened 2024-07-30 14:07 UTC
I'm trying to merge X for Revanced.

Whenever I select the suggested option or leave it unchecked, I'm getting an invalid apk error when installing.

I'm using latest release and trying to merge X v10. 51.1 on stock rooted Pixel Android 14.

![Screenshot_20240730-080430](https://github.com/user-attachments/assets/272a6b48-0b09-4dea-b2ad-1905ef97cd7f)

**Comment by AbdurazaaqMohammed** [comment] 2024-08-02 15:45
Likely caused by https://github.com/AbdurazaaqMohammed/AntiSplit-M/issues/4

Please try the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/tag/1.6.2.1) and send me the logs from inside the app if it still happens

**Comment by AbdurazaaqMohammed** [comment] 2024-08-02 17:27
Can you upload the merged apk and send me the link

**Comment by AbdurazaaqMohammed** [comment] 2024-08-02 17:47
can you upload it on https://litterbox.catbox.moe/ or any file hosting website

If not can you do 2 things for me

1. Install [SAI](https://github.com/Aefyr/SAI), attempt to install the merged APK in it and send me the crash log (it should be more detailed)

2. Open the APK as a zip, extract AndroidManifest.xml and upload that and send me the link

**Comment by AbdurazaaqMohammed** [comment] 2024-08-02 18:09
appears to be related to https://github.com/REAndroid/APKEditor/issues/114, I should have checked it first, sorry for wasting your time

I now pushed a fix for it

**Comment by Vertuhai** [comment] 2024-08-08 04:42
> I'm trying to merge X for Revanced.
> 
> Whenever I select the suggested option or leave it unchecked, I'm getting an invalid apk error when installing.
> 
> I'm using latest release and trying to merge X v10. 51.1 on stock rooted Pixel Android 14.
> 
> ![Screenshot_20240730-080430](https://private-user-images.githubusercontent.com/22119314/353490404-272a6b48-0b09-4dea-b2ad-1905ef97cd7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTI0MjAsIm5iZiI6MTcyMzA5MjEyMCwicGF0aCI6Ii8yMjExOTMxNC8zNTM0OTA0MDQtMjcyYTZiNDgtMGIwOS00ZGVhLWIyYWQtMTkwNWVmOTdjZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOTFhMDE2N2RiM2ZiODUxYWUwZDRhYjdlMTg4M2QyZWQ2ZDBkNzVmNTAwMjQ3NTcyODdiYTFmOTFjNTgyNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r2O0Aj2zOMfgY6mGAAYyEywh1IK_EABI9-vC9IkvGpw)



> File saved successfully

Try installing the latest current version of the application [AntiSplit-M](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/tag/1.6.3.6)

**Comment by m0yP** [comment] 2024-08-08 16:45
> > I'm trying to merge X for Revanced.
> > Whenever I select the suggested option or leave it unchecked, I'm getting an invalid apk error when installing.
> > I'm using latest release and trying to merge X v10. 51.1 on stock rooted Pixel Android 14.
> > ![Screenshot_20240730-080430](https://private-user-images.githubusercontent.com/22119314/353490404-272a6b48-0b09-4dea-b2ad-1905ef97cd7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTI0MjAsIm5iZiI6MTcyMzA5MjEyMCwicGF0aCI6Ii8yMjExOTMxNC8zNTM0OTA0MDQtMjcyYTZiNDgtMGIwOS00ZGVhLWIyYWQtMTkwNWVmOTdjZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOTFhMDE2N2RiM2ZiODUxYWUwZDRhYjdlMTg4M2QyZWQ2ZDBkNzVmNTAwMjQ3NTcyODdiYTFmOTFjNTgyNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r2O0Aj2zOMfgY6mGAAYyEywh1IK_EABI9-vC9IkvGpw)
> 
> Try installing the latest current version of the application [AntiSplit-M](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/tag/1.6.3.6)

Tried latest release and I'm getting the same error.

**Comment by kairusds** [comment] 2024-08-10 12:40
I'm getting this error, while trying to patch X v10.53.0-release.1:

```
java.io.IOException: exception unwrapping private key - java.security.NoSuchAlgorithmException: 1.2.840.113549.1.5.12 SecretKeyFactory not available
com.android.org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.unwrapKey(PKCS12KeyStoreSpi.java:652)
com.android.org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(PKCS12KeyStoreSpi.java:891)
java.security.KeyStore.load(KeyStore.java:1484)
com.reandroid.apkeditor.merge.Merger.run(SourceFile:95)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:34)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)
android.os.AsyncTask$3.call(AsyncTask.java:394)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:923)
```
I'm on stock MIUI Android 11.

**Comment by Vertuhai** [comment] 2024-08-10 13:49
> > > I'm trying to merge X for Revanced.
> > > Whenever I select the suggested option or leave it unchecked, I'm getting an invalid apk error when installing.
> > > I'm using latest release and trying to merge X v10. 51.1 on stock rooted Pixel Android 14.
> > > ![Screenshot_20240730-080430](https://private-user-images.githubusercontent.com/22119314/353490404-272a6b48-0b09-4dea-b2ad-1905ef97cd7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTI0MjAsIm5iZiI6MTcyMzA5MjEyMCwicGF0aCI6Ii8yMjExOTMxNC8zNTM0OTA0MDQtMjcyYTZiNDgtMGIwOS00ZGVhLWIyYWQtMTkwNWVmOTdjZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOTFhMDE2N2RiM2ZiODUxYWUwZDRhYjdlMTg4M2QyZWQ2ZDBkNzVmNTAwMjQ3NTcyODdiYTFmOTFjNTgyNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r2O0Aj2zOMfgY6mGAAYyEywh1IK_EABI9-vC9IkvGpw)
> > 
> > 
> > Try installing the latest current version of the application [AntiSplit-M](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/tag/1.6.3.6)
> 
> Tried latest release and I'm getting the same error.

It’s very strange, I collect it and everything works out fine for me.
Why are you having any problems?!

**Comment by kairusds** [comment] 2024-08-10 13:51
> > > > I'm trying to merge X for Revanced.
> > > > Whenever I select the suggested option or leave it unchecked, I'm getting an invalid apk error when installing.
> > > > I'm using latest release and trying to merge X v10. 51.1 on stock rooted Pixel Android 14.
> > > > ![Screenshot_20240730-080430](https://private-user-images.githubusercontent.com/22119314/353490404-272a6b48-0b09-4dea-b2ad-1905ef97cd7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTI0MjAsIm5iZiI6MTcyMzA5MjEyMCwicGF0aCI6Ii8yMjExOTMxNC8zNTM0OTA0MDQtMjcyYTZiNDgtMGIwOS00ZGVhLWIyYWQtMTkwNWVmOTdjZDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0NDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOTFhMDE2N2RiM2ZiODUxYWUwZDRhYjdlMTg4M2QyZWQ2ZDBkNzVmNTAwMjQ3NTcyODdiYTFmOTFjNTgyNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r2O0Aj2zOMfgY6mGAAYyEywh1IK_EABI9-vC9IkvGpw)
> > > 
> > > 
> > > Try installing the latest current version of the application [AntiSplit-M](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/tag/1.6.3.6)
> > 
> > 
> > Tried latest release and I'm getting the same error.
> 
> It’s very strange, I collect it and everything works out fine for me. Why are you having any problems?!

I'm not sure, maybe it had to do something with certain Android/Java API's not being available to certain Android versions. I tried both the split apks from APKMirror and APKPure, until I eventually had to use the original APKEditor to fix it and had ReVanced sign the apk for me.

**Comment by Vertuhai** [comment] 2024-08-10 14:05
> I'm not sure, maybe it had to do something with certain Android/Java API's not being available to certain Android versions. I tried both the split apks from APKMirror and APKPure, until I eventually had to use the original APKEditor to fix it and had ReVanced sign the apk for me.

Can you somehow show your actions how you do everything?
You can write to me in [Telegram](@Aleksandr_RGC), I will help you figure it out.

**Comment by kairusds** [comment] 2024-08-10 14:08
> > I'm not sure, maybe it had to do something with certain Android/Java API's not being available to certain Android versions. I tried both the split apks from APKMirror and APKPure, until I eventually had to use the original APKEditor to fix it and had ReVanced sign the apk for me.
> 
> Can you somehow show your actions how you do everything? You can write to me in [Telegram](https://t.me/Aleksandr_RGC), I will help you figure it out.

Sorry, I don't use Telegram. I just used the app normally and the apk signing process is the only one failing but the merging process works fine. I remember it signing the apks fine though, on the version of the app before it got its own icon.

**Comment by Vertuhai** [comment] 2024-08-10 14:13
> Sorry, I don't use Telegram. I just used the app normally and the apk signing process is the only one failing but the merging process works fine. I remember it signing the apks fine though, on the version of the app before it got its own icon.

Even now he signs perfectly, especially now the signature is full V1 v2 V3.
Take a video of what you do and how you do it, upload it to a file hosting service and send a link.
I'm very interested in what you can't do.

**Comment by AbdurazaaqMohammed** [comment] 2024-08-10 14:27
> > Sorry, I don't use Telegram. I just used the app normally and the apk signing process is the only one failing but the merging process works fine. I remember it signing the apks fine though, on the version of the app before it got its own icon.
> 
> Even now he signs perfectly, especially now the signature is full V1 v2 V3. Take a video of what you do and how you do it, upload it to a file hosting service and send a link. I'm very interested in what you can't do.

There is no user error, it seems the library to load the key to sign isn't included on some/older Android versions, I will try to add it in the app later

The app doesn't need to be signed to patch with ReVanced

**Comment by kairusds** [comment] 2024-08-10 14:30
> > > Sorry, I don't use Telegram. I just used the app normally and the apk signing process is the only one failing but the merging process works fine. I remember it signing the apks fine though, on the version of the app before it got its own icon.
> > 
> > 
> > Even now he signs perfectly, especially now the signature is full V1 v2 V3. Take a video of what you do and how you do it, upload it to a file hosting service and send a link. I'm very interested in what you can't do.
> 
> There is no user error, it seems the library to load the key to sign isn't included on some/older Android versions, I will try to add it in the app later
> 
> Note an apk doesn't need to be signed to patch with ReVanced

Ty. And yes, I'm aware that apks dont need to be signed for revanced.

**Comment by kairusds** [comment] 2024-08-10 14:33
> > Sorry, I don't use Telegram. I just used the app normally and the apk signing process is the only one failing but the merging process works fine. I remember it signing the apks fine though, on the version of the app before it got its own icon.
> 
> Even now he signs perfectly, especially now the signature is full V1 v2 V3. Take a video of what you do and how you do it, upload it to a file hosting service and send a link. I'm very interested in what you can't do.

Here's the video: https://streamable.com/5lko46

**Comment by AbdurazaaqMohammed** [comment] 2024-08-12 01:15
@kairusds I tried to fix it in the latest release, can you check it and see

**Comment by kairusds** [comment] 2024-08-12 04:28
> @kairusds I tried to fix it in the latest release, can you check it and see

Yeah, it's fixed now.
![Screenshot_2024-08-12-12-27-27-843_com abdurazaaqmohammed AntiSplit](https://github.com/user-attachments/assets/bffc44a9-05ae-41c9-a9aa-6357e2fc694d)

**Comment by 0xrxL** [comment] 2024-08-24 23:48
@AbdurazaaqMohammed guess this isssue can be closed now 👍

**Closed** 2024-09-12 16:27 UTC
