### ISSUE TITLE
0B APK.

### ISSUE THREAD

**Issue by Morafoka69** [AbdurazaaqMohammed/AntiSplit-M#28] opened 2024-08-19 17:29 UTC
This is not my first time using this Antisplit app. 

I just downloaded the latest release and tried to use it on a Twitter apkm file I got from Apkmirror.

It patches and gives a 0B output. I used exactly your settings in the screenshot you posted in your Repo at first and it didn't work. 

Then I used this:
![Screenshot_20240819-182738](https://github.com/user-attachments/assets/288069c0-d48d-43e7-82fe-a9cb357d4518)

Didn't work too. Please help me.

**Comment by AbdurazaaqMohammed** [comment] 2024-08-19 19:59
Sorry I think I broke something while changing the settings menu, it should be fixed in the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest), if it still happens please send me the log from inside the app

**Comment by Morafoka69** [comment] 2024-08-19 20:11
> Sorry I think I broke something while changing the settings menu, it should be fixed in the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest), if it still happens please send me the log from inside the app

Thanks a lot! I'll get back to you.

**Comment by Morafoka69** [comment] 2024-08-19 20:34
I just downloaded the latest release.

I tried antisplitting the apkm file and it finished, but when I went to install it, it told me that there was a problem parsing the package.

I tried to antisplit again so that I can copy the logs and paste them here, but the AntiSplit-M app started crashing.

I tried opening it again, and it crashed again—I couldn't use the app at all.

I even cleared the app data, still crashing. Uninstall and reinstall, still crashing.

Please come to my aid.

**Comment by AbdurazaaqMohammed** [comment] 2024-08-19 21:36
Sorry, please check the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest) again, I think it was crashing if checking for update failed for any reason

> I tried antisplitting the apkm file and it finished, but when I went to install it, it told me that there was a problem parsing the package.

Make sure the option to sign APK is enabled and try selecting all splits to check if the app is not selecting the right ones for some reason

**Comment by Morafoka69** [comment] 2024-08-20 00:00
I'm back. I did everything you said. I downloaded the latest release and tried again. It showed the app size, but it couldn't be installed. 




> Make sure the option to sign APK is enabled and try selecting all splits to check if the app is not selecting the right ones for some reason

Signing APK was turned on already everytime. I made sure of that even before making this issue.

Also, I noticed something. Whenever I disable the _Fix For Revanced_ option, the apk file has the app icon shown in the file manager and it can be installed. But the installed app stops as soon as I open it. I can't even use it at all.

On the other hand, when the _Fix For Revanced_ option is enabled, the app icon is not shown in the file manager and I can't even install the app.
Attached is a screenshot:

![Screenshot_20240820-004341](https://github.com/user-attachments/assets/76c39ae7-9fc9-43c5-b0f0-699051c92680)

x_1.apk and x_2.apk are the outputs of following your instructions to the letter.
x_w_ffr.apk (X without_Fix For Revanced) was the output of antisplitting without enabling the _Fix For Revanced_ option.
x_piko.apk is the output of patching x_w_ffr **with your forked Revanced Manager**. Shockingly, I was able to patch it without any signing errors as it should have, but it did the same thing—it stops immediately after opening; I can't even use the app at all. I just wanted to let you know.

**Comment by AbdurazaaqMohammed** [comment] 2024-08-20 00:36
I notice in your first screenshot the APK only has base, en, arm64 and xxxhdpi, I think this is beta/alpha version from APKMirror, so I tested with those versions. But I can only replicate the app crashing if I used "Select splits for your device specifications", because my phone is xxhdpi, so it didn't select any resources. If I select all splits it works, maybe on some non xxxhdpi phones it will crash as well.

> On the other hand, when the Fix For Revanced option is enabled, the app icon is not shown in the file manager and I can't even install the app.

I can't replicate this at all, but I will try using a different approach to fix it

**Comment by Morafoka69** [comment] 2024-08-20 00:41
> I notice in your first screenshot the APK only has base, en, arm64 and xxxhdpi, I think this is beta/alpha version from APKMirror, so I tested with those versions

The latest screenshot I posted about 3 apks were from the latest stable release I just downloaded. 

> . If I select all splits it works, maybe on some non xxxhdpi phones it will crash as well.

Please what do you suggest I do? TIA.

**Comment by AbdurazaaqMohammed** [comment] 2024-08-20 01:06
> The latest screenshot I posted about 3 apks were from the latest stable release I just downloaded.

Are you sure? And you select all splits? When I select all splits the merged APK is nearly 80MB.

> Please what do you suggest I do? TIA.

Can you upload any one of the merged APKs on any site like https://litterbox.catbox.moe/ and send me the link so I can try to see what the problem is

And try merging any other app to see if it works, here is a small one just for example https://www.apkmirror.com/apk/rarlab-published-by-win-rar-gmbh/rar/rar-7-01-build123-release/rar-7-01-build123-5-android-apk-download/

**Comment by 0xrxL** [comment] 2024-08-22 18:37
> This is not my first time using this Antisplit app.
> 
> I just downloaded the latest release and tried to use it on a Twitter apkm file I got from Apkmirror.
> 
> It patches and gives a 0B output. I used exactly your settings in the screenshot you posted in your Repo at first and it didn't work.
> 
> Then I used this: ![Screenshot_20240819-182738](https://private-user-images.githubusercontent.com/155040570/359190524-288069c0-d48d-43e7-82fe-a9cb357d4518.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTE4NjAsIm5iZiI6MTcyNDM1MTU2MCwicGF0aCI6Ii8xNTUwNDA1NzAvMzU5MTkwNTI0LTI4ODA2OWMwLWQ0OGQtNDNlNy04MmZlLWE5Y2IzNTdkNDUxOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxODMyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzAxM2E2Njg3ZjAwYmYwNGY3Zjk1OGE5YzJmMDJmMjFhZDAxMGI3ZTFiYTc4ZGFhNzI3ZjMzY2U5NzVhN2RiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4KRFQvE2vJ4hEFQBrZ0VuRVdsvAsVlO0dbypnSRANzA)
> 
> Didn't work too. Please help me.

I can reproduce your issue...but it's not a real issue, because it happens when the merging task it's not finished yet. On latest app version a loading animation has been added, to prevent misunderstandings.

Try to merge some splits again.

**Comment by Morafoka69** [comment] 2024-09-10 13:33
It's been fixed. Thanks.

Also, please I have a question to ask. Is Enabling Pre-releases available in your forked Revanced Manager? I'm sorry for opening it here but I didn't want to open a new issue in that repo.

TIA!

**Comment by AbdurazaaqMohammed** [comment] 2024-09-12 16:25
I don't know, I don't see that option in regular ReVanced manager

**Closed by AbdurazaaqMohammed** 2024-09-12 16:25 UTC
