### ISSUE TITLE
Doesn't save APK to relative path in Downloads in Android file picker with `Ask where to save the file each time` disabled

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#34] opened 2024-08-20 20:46 UTC
https://github.com/user-attachments/assets/ce906e55-bb59-45c6-a90a-c85fc8bcfbbc

**Comment by AbdurazaaqMohammed** [comment] 2024-08-21 05:47
The problem is that when you select a file in the Android file picker, it doesn't return a real filepath, but something called a Uri, and from Downloads in its sidebar specifically, it doesn't even have a normal path, it looks like this `/document/msf:1000617719`. If you open the device storage and go into Download folder or any other folder from there it works.

I don't think you can get the relative path from Downloads in the sidebar, the code I used just gets the file name and returns the base Download folder plus the file name.

```
try (Cursor cursor = context.getContentResolver().query(uri, new String[]{MediaStore.MediaColumns.DISPLAY_NAME}, null, null, null)) {
                if (cursor != null && cursor.moveToFirst()) {
                    String fileName = cursor.getString(0);
                    String path = Environment.getExternalStorageDirectory() + "/Download/" + fileName;
                    if (!TextUtils.isEmpty(path)) {
                        return path;
                    }
                }
            }
```

**Comment by AbdurazaaqMohammed** [comment] 2024-09-12 15:21
should be fixed in [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

**Closed by AbdurazaaqMohammed** 2024-09-12 15:21 UTC
