### ISSUE TITLE
Wrong file extension name shown in logs

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#36] opened 2024-08-20 21:11 UTC
It shows `.apk` instead of `.apkm`:

https://github.com/user-attachments/assets/e6e0df84-6bcf-4700-8bed-a7ed6fb245ce

**Comment by AbdurazaaqMohammed** [comment] 2024-08-21 05:34
This is not a bug, it's showing where the merged file will be saved, including the filename of that merged file

**Closed by AbdurazaaqMohammed** 2024-08-21 05:34 UTC
