### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MAXBURAOT** [AbdurazaaqMohammed/AntiSplit-M#107] opened 2024-10-21 11:40 UTC
java.lang.RuntimeException: com.abdurazaaqmohammed.AntiSplit.main.MismatchedSplitsException: Error: Key (the app will not run without it) split (config.x86.apk) has a mismatched version code.com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:338)com.reandroid.apkeditor.merge.Merger.run(SourceFile:78)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)android.os.AsyncTask$3.call(AsyncTask.java:394)java.util.concurrent.FutureTask.run(FutureTask.java:264)android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)java.lang.Thread.run(Thread.java:1012)Searching apk files…/document/primary:Download/aaa/pair/Pair/Music Speed Changer_13.0.0-pl_apkcombo.com.xapkExtracted com.smp.musicspeed.apkExtracted config.x86.apkExtracted config.xxhdpi.apkExtracted config.x86_64.apkExtracted config.mdpi.apkExtracted config.hdpi.apkExtracted config.ldpi.apkExtracted config.tvdpi.apkExtracted config.xxxhdpi.apkExtracted config.arm64_v8a.apkExtracted config.xhdpi.apkExtracted config.armeabi_v7a.apkSkipping manifest.json: Not an APK fileSkipping APKComboInstaller.url: Not an APK fileSkipping icon.png: Not an APK fileFound apk files: 12config.hdpi.apk version code does not match that of base.apkconfig.xxxhdpi.apk version code does not match that of base.apkconfig.tvdpi.apk version code does not match that of base.apk

**Comment by AbdurazaaqMohammed** [comment] 2024-10-24 03:31
Duplicate of https://github.com/AbdurazaaqMohammed/AntiSplit-M/issues/61

**Closed as not planned by AbdurazaaqMohammed** 2024-10-24 03:31 UTC
