### ISSUE TITLE
Crash Report windyapp arm64 only

### ISSUE THREAD

**Issue by MAXBURAOT** [AbdurazaaqMohammed/AntiSplit-M#78] opened 2024-09-13 03:04 UTC
java.lang.RuntimeException: com.abdurazaaqmohammed.AntiSplit.main.MismatchedSplitsException: Error: All DPI/resource splits selected have a mismatched version code.com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:394)com.reandroid.apkeditor.merge.Merger.run(SourceFile:56)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)android.os.AsyncTask$3.call(AsyncTask.java:394)java.util.concurrent.FutureTask.run(FutureTask.java:264)android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)java.lang.Thread.run(Thread.java:1012)Output directory: /storage/emulated/0/Download/aaa/pair/Windy.app_50.1.0_apkcombo.com_antisplit.apkSearching apk files…/document/primary:Download/aaa/pair/Windy.app_50.1.0_apkcombo.com.xapkExtracted co.windyapp.android.apkSkipping config.x86.apk: UnselectedSkipping config.ja.apk: UnselectedSkipping config.xxhdpi.apk: UnselectedSkipping config.it.apk: UnselectedSkipping config.x86_64.apk: UnselectedSkipping config.th.apk: UnselectedSkipping config.nl.apk: UnselectedSkipping config.mdpi.apk: UnselectedSkipping config.de.apk: UnselectedExtracted config.hdpi.apkExtracted config.en.apkSkipping config.zh.apk: UnselectedSkipping config.ldpi.apk: UnselectedSkipping config.ru.apk: UnselectedSkipping config.tvdpi.apk: UnselectedSkipping config.pt.apk: UnselectedSkipping config.pl.apk: UnselectedSkipping config.es.apk: UnselectedSkipping config.ms.apk: UnselectedSkipping config.fi.apk: UnselectedSkipping config.ar.apk: UnselectedSkipping config.hi.apk: UnselectedSkipping config.xxxhdpi.apk: UnselectedSkipping config.vi.apk: UnselectedSkipping config.in.apk: UnselectedSkipping config.fr.apk: UnselectedExtracted config.arm64_v8a.apkSkipping config.xhdpi.apk: UnselectedSkipping config.armeabi_v7a.apk: Unselected

**Comment by AbdurazaaqMohammed** [comment] 2024-09-13 04:07
Duplicate of https://github.com/AbdurazaaqMohammed/AntiSplit-M/issues/61, please read my message there, BTW, maybe you know this already, but Windy.app has Pairip/Google加固 Integrity, but in case you are trying to patch this app with ReVanced it won't work, you should try the last version that is not split or look for alternative pre patched sources.

**Closed as completed by AbdurazaaqMohammed** 2024-09-13 04:07 UTC
