### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Mohidinmir** [AbdurazaaqMohammed/AntiSplit-M#106] opened 2024-10-14 14:25 UTC
java.io.FileNotFoundException: No '*.apk' files in directory: /data/user/0/com.abdurazaaqmohammed.AntiSplit/cachecom.reandroid.apk.ApkBundle.loadApkDirectory(SourceFile:379)com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:332)com.reandroid.apkeditor.merge.Merger.run(SourceFile:78)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)android.os.AsyncTask$3.call(AsyncTask.java:394)java.util.concurrent.FutureTask.run(FutureTask.java:264)android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)java.lang.Thread.run(Thread.java:1012)Searching apk files…/document/primary:A/Apktool_M_v2.4.0-240820(2024082001).apkSkipping res/drawable/abc_list_selector_background_transition_holo_dark.xml: Not an APK fileSkipping res/drawable/ic_down_dark.png: Not an APK fileSkipping res/drawable-v21/abc_btn_colored_material.xml: Not an APK fileSkipping res/drawable-v24/ic_select_all.xml: Not an APK fileSkipping res/drawable-xxhdpi-v4/abc_textfield_default_mtrl_alpha.9.png: Not an APK fileSkipping res/drawable/ic_inverse.png: Not an APK fileSkipping res/drawable-v24/ic_delete.xml: Not an APK fileSkipping res/drawable-xxxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png: Not an APK fileSkipping assets/android.dex: Not an APK fileSkipping res/drawable-v24/ic_nav_disable.xml: Not an APK fileSkipping res/layout/files.xml: Not an APK fileSkipping res/anim/btn_radio_to_on_mtrl_ring_outer_path_animation.xml: Not an APK fileSkipping res/drawable-v24/ic_action_comm_dark.xml: Not an APK fileSkipping res/layout/abc_cascading_menu_item_layout.xml: Not an APK fileSkipping res/menu/close_file.xml: Not an APK fileSkipping res/drawable/border.xml: Not an APK fileSkipping res/drawable/bg_btn_black.xml: Not an APK fileSkipping res/drawable/ic_action_comm.png: Not an APK fileSkipping res/animator/fragment_fade_enter.xml: Not an APK fileSkipping res/xml/preference_updater.xml: Not an APK fileSkipping res/drawable-hdpi-v4/abc_cab_background_top_mtrl_alpha.9.png: Not an APK fileSkipping res/drawable-hdpi-v4/notification_bg_normal.9.png: Not an APK fileSkipping res/drawable/abc_btn_check_material.xml: Not an APK fileSkipping lib/x86/libpngquantandroid.so: Not an APK fileSkipping res/layout/title.xml: Not an APK fileSkipping res/drawable/ic_bookmark_dark.png: Not an APK fileSkipping res/layout/abc_tooltip.xml: Not an APK fileSkipping res/menu/app.xml: Not an APK fileSkipping assets/key/platform.x509.pem: Not an APK fileSkipping res/drawable-v24/ic_paste_light.xml: Not an APK fileSkipping res/drawable/ic_action_up.png: Not an APK fileSkipping res/drawable/ic_faq_dark.png: Not an APK fileSkipping res/drawable/ic_close.png: Not an APK fileSkipping res/drawable/ic_folder.png: Not an APK fileSkipping res/drawable/ic_settings_light.png: Not an APK fileSkipping res/drawable/ic_top.png: Not an APK fileSkipping res/layout/files_entry.xml: Not an APK fileSkipping lib/x86_64/libpngquantandroid.so: Not an APK fileSkipping res/drawable/abc_dialog_material_background.xml: Not an APK fileSkipping res/drawable-xhdpi-v4/abc_btn_radio_to_on_mtrl_015.png: Not an APK fileSkipping org/objectweb/asm/xml/asm-xml.dtd: Not an APK fileSkipping res/drawable-hdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png: Not an APK fileSkipping res/drawable/ic_action_goto.png: Not an APK fileSkipping res/drawable/ic_dex.png: Not an APK fileSkipping res/drawable-hdpi-v4/ic_notification.png: Not an APK fileSkipping res/drawable-hdpi-v4/abc_list_longpressed_holo.9.png: Not an APK fileSkipping res/menu/apks.xml: Not an APK fileSkipping res/drawable-v24/ic_from_uni_dark.xml: Not an APK fileSkipping res/animator/fragment_fade_exit.xml: Not an APK fileSkipping res/color/abc_btn_colored_text_material.xml: Not an APK fileSkipping res/drawable-xxxhdpi-v4/abc_btn_radio_to_on_mtrl_015.png: Not an APK fileSkipping res/drawable-xhdpi-v4/abc_btn_check_to_on_mtrl_000.png: Not an APK fileSkipping res/menu/settings.xml: Not an APK fileSkipping assets/killer/killer.dex: Not an APK fileSkipping org/objectweb/asm/tree/analysis/package.html: Not an APK fileSkipping res/dr

**Comment by drogga** [comment] 2024-10-15 17:17
The log is a mess, where there should be new lines, there aren't, but the text is stitched together, making it barely readable as is - maybe try putting it in code...?, anyway Do you by any chance try to AntiSplit/Merge an .apk file, instead of a bundle/splits, like `Apktool_M_v2.4.0-240820(2024082001).apk` ?

**Comment by drogga** [comment] 2024-10-16 06:42
@Mohidinmir The log is a mess, where there should be new lines, there aren't, but instead the text is stitched together without even a space of where there should be a new line (is what I see), making it barely readable as is - maybe try putting it in `code`..., anyway, do you by any chance try to AntiSplit/Merge an .apk file, instead of a bundle/splits, like `Apktool_M_v2.4.0-240820(2024082001).apk` ?, if that's the case, then please close this ticket.

**Comment by AbdurazaaqMohammed** [comment] 2024-10-24 03:28
> Apktool_M_v2.4.0-240820(2024082001).apk

@Mohidinmir You are trying to merge a single regular APK. This app is for merging several splits (base.apk, config.armeabi_v7a.apk, config.xxhdpi.apk etc.) or split APKs (APKS/XAPK/APKM, just archives containing the former).

> The log is a mess, where there should be new lines

I [did add](https://github.com/AbdurazaaqMohammed/AntiSplit-M/blob/e503af6be82b93d34adde6b1cca8ec53eed3c2ae/app/src/main/java/com/abdurazaaqmohammed/AntiSplit/main/MainActivity.java#L1017) newlines in the app, I think it maybe browser problem not recognizing or handling properly newline \n in URL

**Closed as completed by AbdurazaaqMohammed** 2024-10-24 03:28 UTC

**Comment by drogga** [comment] 2024-10-24 07:44
If you mean that the issue is on my end with Chromium based browsers - I'm pretty sure it isn't, if anything - It's MarkDown (logs from & in any other projects show up just fine in GH or what/wherever else).

IDT it's the case here, but something might happen between the Copy>Paste _(system/KB's clipboard unnecessarily sanitizing things it shouldn't - I've encountered this multiple times)_ or/and when opening a new issue ticket directly from there _(if supported - I've never tried it that way)_.

It's also cropped _(clipboards can and do this with long text sometimes)_ and I don't think anymore that putting it in `code` will make it more readable.

Probably not recommend, but maybe you can also test with `\r` ?

**Comment by AbdurazaaqMohammed** [comment] 2024-10-24 20:24
> If you mean that the issue is on my end with Chromium based browsers

No, I mean the button in the app in the error dialog "Create GitHub Issue" which will open a link in user's browser with the log included as the description in the URL (It fills title also as "Crash Report", you can see multiple issues with it). So it's not a clipboard problem, I don't know which browser has this issue

**Comment by drogga** [comment] 2024-10-24 22:15
I think you mean an intent (like how many apps provide a option to send an E-Mail to the dev., including some info/logs as message text and often even a subject title) and it's understandable why it doesn't respect or keep it intact, removing/ignoring new lines and I don't think it's browser specific as URLs are meant to be single line plain text, as for the default "Crash Report" as subject title - it's kind of misleading, because hardly any of those are actually crashes, so I suggest either not inject a title at all, or use something else, part of the log text (the actual reason) or just "Report", as long as it's not an actual crash, but then IDK if the app will capture itself as say how Scoop/LogFox can from the logs, anyway I will not pretend that I understand those things very much, especially on a coding level, but you can probably look at (if you haven't) how other apps inject the message, currently I can only thing of NewPipe, besides the ones with E-Mail options for a feature request, general feedback or a bug/crash report.

**Comment by drogga** [comment] 2024-10-26 09:53
I think you mean an URI intent (like how many apps provide a option to send an E-Mail to the dev., including some info/logs as message body text and often even a subject title) and it's understandable why it doesn't respect or keep it intact, removing/ignoring new lines and I don't think it's browser specific as URLs are meant to be single line plain text, as for the default "Crash Report" as subject title - it's kind of misleading, because hardly any of those are actually crashes, so I suggest either not inject a title at all, letting the user type it before creating the issue ticket, or use something else, part of the log text (the actual reason) or just "Report", as long as it's not an actual crash, but then IDK if the app will capture itself as say how Scoop/LogFox can from the logs, anyway I will not pretend that I understand those things very much, especially on a coding level, but you can probably look at (if you haven't) how other open source apps inject the message body, currently I can only think of NewPipe, besides the ones with E-Mail options for a feature request, general feedback or a bug/crash report.

Btw - is `"<br />"` at line 854 in MainActivity.java correct ?

**Comment by AbdurazaaqMohammed** [comment] 2024-10-26 18:29
Well it would be a crash if I didn't catch it and display it in the dialog. And yes, it's parse from HTML so that I can put HTML in the changelog and display it

**Comment by drogga** [comment] 2024-10-26 22:17
The thing is that those shouldn't be crashes at all and so long and detailed, I mean I like details, but by the looks of it - the users don't seem to know what they are doing and the logs, such as the OP one don't seem help those users that report them, and I'm afraid that as long as there are such, and not replaced by a pop-up msg. for example saying something like "Not a bundle", there will always be such similar tickets. I understand that those logs basically come from the source REAndroid/APKEditor (I've never used it because it doesn't have a GUI). At least it's quiet now regarding the tickets.

That's all.

**Comment by drogga** [comment] 2024-10-28 19:03
@AbdurazaaqMohammed - v.**2.1.1**:
`Add some additional logs to crash report to help diagnose issues` -> I haven't tested it, but I guess it's related to our discussion here ? [Thanks]
`Fix a bug merging some APKs that contain classes.dex files in subfolders` -> Please if necessary (probably is) apply such to the v1.x and the other non-MaterialYou changes since the last release which was 1.6.6.3, which are applicable and makes sense for the 1.x too, like core functionality. [TYia]

`update usage video` -> YT desktop site - the GH link in the description is cropped and not clickable, IDK if it's the same on mobile, but if you can fix it and you haven't used a /releases path, please do so, because from the previous one it seems like even tho you linked it in the comments, there are still individuals that don't know how to get it from GH, even tho it's super simple.
In future consider maybe using TTS for narrating, getting rid of the on screen text, or maybe remove the audio and use forced captions (It's an YT thing, different from hardcoded subtitles in the video), the current auto-generated ENg ones aren't the best, IDK if you can edit them to use as custom for the video.
It can be seen near the end of the video that in the `Select splits` prompt that the last 3 options (all selected or any of them) don't select the `base.apk`, if it doesn't include it anyway when pressing `OK`, I guess it will skip it and IDT that will produce a working app, unless I'm wrong and it's somehow intentional or like this only in the video for some reason.

The 3 options:
Select architecture for your device
Select screen widths for you device
Select language for your device

**Comment by AbdurazaaqMohammed** [comment] 2024-10-28 19:38
YouTube don't let me pin comment or add clickable link in description thanks to new restrictions

> Select architecture for your device
> Select screen widths for you device
> Select language for your device

base.apk is not mentioned here, it's valid usage to merge only some files and then merge that merged file with the base later. This is not actually working right now, it shows the mismatched splits error because it tries to check the version code against base.apk but since there is no base.apk it fails, I need to fix this.

Anyway, base.apk should not be selected when pressed OK, but I could make it selected by default when opening the dialog.

**Comment by drogga** [comment] 2024-10-28 20:03
`YouTube don't let me pin comment or add clickable link in description thanks to new restrictions` -> Damn, tho anything goes and is allowed for big/popular channels. I'm not aware of the new restrictions. Thanks Google.

`I need to fix this.`
`Anyway, base.apk should not be selected when pressed OK, but I could make it selected by default when opening the dialog.`
-> OK, please do so when you have time. It makes sense and sounds good. Thanks.
