### ISSUE TITLE
Crash Report Windyapp

### ISSUE THREAD

**Issue by MAXBURAOT** [AbdurazaaqMohammed/AntiSplit-M#77] opened 2024-09-13 03:02 UTC
java.lang.RuntimeException: com.abdurazaaqmohammed.AntiSplit.main.MismatchedSplitsException: Error: Key (the app will not run without it) split (config.x86.apk) has a mismatched version code.com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:394)com.reandroid.apkeditor.merge.Merger.run(SourceFile:56)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)android.os.AsyncTask$3.call(AsyncTask.java:394)java.util.concurrent.FutureTask.run(FutureTask.java:264)android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)java.lang.Thread.run(Thread.java:1012)Output directory: /storage/emulated/0/Download/aaa/pair/Windy.app_50.1.0_apkcombo.com_antisplit.apkSearching apk files…/document/primary:Download/aaa/pair/Windy.app_50.1.0_apkcombo.com.xapkExtracted co.windyapp.android.apkExtracted config.x86.apkExtracted config.ja.apkExtracted config.xxhdpi.apkExtracted config.it.apkExtracted config.x86_64.apkExtracted config.th.apkExtracted config.nl.apkExtracted config.mdpi.apkExtracted config.de.apkExtracted config.hdpi.apkExtracted config.en.apkExtracted config.zh.apkExtracted config.ldpi.apkExtracted config.ru.apkExtracted config.tvdpi.apkExtracted config.pt.apkExtracted config.pl.apkExtracted config.es.apkExtracted config.ms.apkExtracted config.fi.apkExtracted config.ar.apkExtracted config.hi.apkExtracted config.xxxhdpi.apkExtracted config.vi.apkExtracted config.in.apkExtracted config.fr.apkExtracted config.arm64_v8a.apkExtracted config.xhdpi.apkExtracted config.armeabi_v7a.apkSkipping manifest.json: Not an APK fileSkipping APKComboInstaller.url: Not an APK fileSkipping icon.png: Not an APK fileFound apk files: 30

**Comment by AbdurazaaqMohammed** [comment] 2024-09-13 04:06
Duplicate of https://github.com/AbdurazaaqMohammed/AntiSplit-M/issues/61, please read my message there, BTW, maybe you know this already, but Windy.app has Pairip/Google加固 Integrity, but in case you are trying to patch this app with ReVanced it won't work, you should try the last version that is not split or look for alternative pre patched sources.

**Closed as completed by AbdurazaaqMohammed** 2024-09-13 04:06 UTC
